### PR TITLE
documents: harvest records from HEG

### LINKED ISSUE #429: Import data from HEG sets
Step to solve this issue:

- [x] Create a CLI for harvesting records from an affiliation.
- [x] Connect to HEG FTP and download file for the affiliation.
- [x] Iterate records and convert JSON.
- [x] Create a document and persist it for each records.

### PR DESCRIPTION
**Pull request by sebastiendeleze**
* Harvests records from HEG (CrossRef or Medline sources).
* Creates a CLI command for harvesting from affiliations.
* Creates a class to retrieve records from HEG repository.
* Adds classes for formatting records from CrossRef and Medline.
* Checks status code when file is added to a document from an URL.
* Adds `afr` in known languages.
* Moves `chunks` function into utils functions.
* Updates the document when the record is already registered.
* Adds a method to get or create an organisation.
* Allows to store organisation with PID containing `-`.
* Closes #429.

Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>

### CODE REVIEW

**Comment by pronguen** [comment]
- [ ] The DOI is always imported twice, once as a DOI, once as an HEG local identifier. Why? We can probably avoid the second one.
- [ ] Some records have no PDF ([example: Invariant NKT cells contribute to chronic...](https://sonardev.test.rero.ch/global/documents/7))
- [ ] The Medline `mesh_terms` could be imported as `subject.label` (with source= MeSH) and displayed.
- [ ] @mmo Should we create a property in our model to receive the OA status (gold, bronze, etc.)? If yes, should this be part of the deposit form, or only of the document editor?
- [ ] [nice to have:] Add field `partOf.document.identifiedBy` so that we can take and display the journal ISSN for each article.
- [ ] It seems that the `numberingVolume`/`numberingIssues`/`numberingPages` are not present in the Medline record, but usually are in the Crossref record. In Medline, this data exist: maybe ask Julien?

**Comment by sebastiendeleze** [comment]
> * [ ]  Some records have no PDF ([example: Invariant NKT cells contribute to chronic...](https://sonardev.test.rero.ch/global/documents/7))

This is because PDF URL is not accessible (captcha): https://ashpublications.org/blood/article-pdf/129/26/3440/1401462/blood751065.pdf

> * [ ]  [nice to have:] Add field `partOf.document.identifiedBy` so that we can take and display the journal ISSN for each article.

Could you precise the property, is it `journal_issn_l` in the unpaywall record?

> * [ ]  It seems that the `numberingVolume`/`numberingIssues`/`numberingPages` are not present in the Medline record, but usually are in the Crossref record. In Medline, this data exist: maybe ask Julien?

Maybe I can merge the two sources, with precedence for Medline, what do you think?

**Comment by pronguen** [comment]
> > * [ ]   Some records have no PDF ([example: Invariant NKT cells contribute to chronic...](https://sonardev.test.rero.ch/global/documents/7))
> 
> This is because PDF URL is not accessible (captcha): https://ashpublications.org/blood/article-pdf/129/26/3440/1401462/blood751065.pdf

For the end user, it is almost useless to display the metadata without indicating the URL. Can we just display the link, even if we don't have a thumbnail?

> > * [ ]   [nice to have:] Add field `partOf.document.identifiedBy` so that we can take and display the journal ISSN for each article.
> 
> Could you precise the property, is it `journal_issn_l` in the unpaywall record?

I would take it in CrossRef: we can take the `issn-type` dont le type est `electronic`.

```json
"issn-type": [
          {
            "value": "0301-1526",
            "type": "print"
          },
          {
            "value": "1664-2872",
            "type": "electronic"
          }
        ]
```

> > * [ ]   It seems that the `numberingVolume`/`numberingIssues`/`numberingPages` are not present in the Medline record, but usually are in the Crossref record. In Medline, this data exist: maybe ask Julien?
> 
> Maybe I can merge the two sources, with precedence for Medline, what do you think?

Do you have to merge them? Ideally, you pick the info in one or another source according to your needs. In some cases, you may have to check if the data exist in Medline, and if not, check in Crossref...

**Comment by sebastiendeleze** [comment]
@pronguen For some PDFs, I cannot add a link to them, because the URL is empty:

```
"unpaywall_record": {
    "_id": "10.1161/circulationaha.119.040167",
    "title": "Defining High Bleeding Risk in Patients Undergoing Percutaneous Coronary Intervention: A Consensus Document From the Academic Research Consortium for High Bleeding Risk",
    "best_oa_location": {
        ...
        "url_for_pdf": null
    },
    ...
}
```

**Comment by pronguen** [comment]
> @pronguen For some PDFs, I cannot add a link to them, because the URL is empty:

Can we just hide these documents without URL? It is not worse displaying the metadata if the user cannot access the PDF.

**Pull request merged**
