### PR TITLE
documents: improve detail views

### PR DESCRIPTION
**Pull request by sebastiendeleze**
* Improves detail views for documents.
* Removes unused macros.
* Removes unused filters functions.
* Completes JSON test document.

Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>

### CODE REVIEW

**Comment by mmo** [comment]
>    * The affiliation is not displayed if there is no controlled affiliation > a solution? (currently, we show the affiliation as tooltip on the controlled affiliation)

Yes, the affiliation should be displayed in all cases. In addition, we might consider (now or later) to add a link to controlled affiliations allowing the user to bounce to a new search having that affiliation as criterion (and activating the corresponding facet entry).

>    * The role is not displayed > should we display it only if it is not "creator" (`cre`)?

Sure, we should show the distinction between creators and the other roles. The proposal of showing the role label only for non-creators seems interesting. Later on, we might add the role label to creators as well, based on feedback from our users or clients.

**Comment by pronguen** [comment]
@sebastiendeleze Result of a brief discussion with Miguel:

>    * The affiliation is not displayed if there is no controlled affiliation > a solution? (currently, we show the affiliation as tooltip on the controlled affiliation)

Solution: display the controlled affiliation in the tooltip, and the other one next to the author (the inverse of current situation).

>    * The role is not displayed > should we display it only if it is not "creator" (`cre`)?

Solution: display creators first, without role indication, and then the other roles (with indication in brackets, cf. image below)

image

Mockup has been updated on Switchdrive (`\sonar_shared\WP3_user_interface\mockups\search_v4.pdf`)

**Comment by sebastiendeleze** [comment]
Some modifications have been done, here's my feedback:

> * Field ORCID not displayed in professional editor (it is impossible to add an ORCID)

I will correct that in the issue dedicated for the editor https://github.com/rero/sonar/issues/230.

> * Bug keeping only first author when editing a document (i think the bug is already described for RERO ILS)

That's right and will be corrected in next `ng-core` release.

> * Thesis imported from RERO DOC don't have a date 😞 Date of thesis is stored in MARC field 502$9. We should update the conversions AND the date facet for this case.

This field will be imported in https://github.com/rero/sonar/issues/254, which is ready to review. What's the priority of this field against other dates?

> * According to mockups:
>   
>   * The affiliation is not displayed if there is no controlled affiliation > a solution?

OK, corrected taking care of your additional comments.

>   * The role is not displayed > should we display it only if it is not "creator" (`cre`)?

OK, corrected taking care of your additional comments.

> * If an author has the role `dgs`, it is not displayed in the author list (brief + detailed view). It even creates a small punctuation error (see screenshot below). Check also other roles.
>   image

Corrected.

> * ORCID should be stored in the data model as identifiers of type "bf:Local". There are now stored as "bf:Doi"

Corrected

> * The abstract should be displayed in the interface language first (brief + detailed view). It is currently displayed in German first, whatever the interface language is (test this [example](https://sonardev.test.rero.ch/organisation/sonar/documents/158))

Corrected

> * [detail] Field `controlled_affiliation` should not be displayed/editable in professional editor

This will be done in https://github.com/rero/sonar/issues/230.

> * [detail] The preview at the end of the process "Deposit a publication" doesn't correspond to current detailed view.

Could you create another specific issue for that?

**Comment by sebastiendeleze** [comment]
> Great corrections, everything works 👌

Thanks!

> I would just put the roles with first character in lower case.

Done! This will be available after next deployment.

**Pull request merged**
